version: '3'
services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catechdojo
      MYSQL_USER: catechdojo
      MYSQL_PASSWORD: catechdojo
    volumes:
    - ./db/mysql_data:/var/lib/mysql
    - ./db/mysql_init:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  web:
    build: .
    command: bash -c "go run main.go data.go"
    tty: true
    volumes:
    - .:/go/src/web
    ports:
    - "8080:8080"
    depends_on:
      - db
